version: '3.8'

services:
  ngotelin_db:
    image: postgres:15-alpine
    container_name: ngotelin_postgres_container
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432" # Port diambil dari .env (di laptop gue konflik)
    volumes:
      - ngotelin_postgres_data:/var/lib/postgresql/data

  # GUI Database (PgAdmin)gw
  ngotelin_pgadmin:
    image: dpage/pgadmin4
    container_name: ngotelin_pgadmin_container
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - ngotelin_db

# Management Volume Data
volumes:
  ngotelin_postgres_data: