@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJ1ZGlAbmdvdGVsaW4uY29tIiwic3ViIjoiYjRmNWE0NGMtN2RhMy00MzA0LTkzOGItZjEzOTg3NTU2MjQ5Iiwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODM3ODkyNDIsImV4cCI6MTc4Mzg3NTY0Mn0.cjnkSi1xnMVUBqa2IO7-3VT-_qlGPx25c5AxYkYQBs8
@userId = 6210b2d2-175b-4f64-a184-51174d8e193a
@resourceId = ba81f869-3ae5-49b0-8209-972b71a5edac
@resourceIdVVIP = f3796c4c-016c-4c6b-a2f7-a2cb531e47d9  
@scheduleId = 59e07058-b436-4aca-ae78-7fad7770f505
@bookingId = d88ba27f-0092-41cd-932f-c6f49f32316e
@notificationId = 629eeae3-db89-4bce-86b4-5ff49476e66c
@reviewId = 39078c3d-d53b-45e8-b501-9c6f3b1300be
### =========================================
### 1. AUTHENTICATION
### =========================================

# Login (Pastikan email dan password sesuai database)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "gibran@mail.ngotel",
  "password": "11111111"
}

### =========================================
### 2. USERS
### =========================================

# Get All Users
GET {{baseUrl}}/user
# Authorization: Bearer {{token}}

###
# Get Single User by ID
GET {{baseUrl}}/user/{{userId}}

###
# Create New User
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "password": "password123",
  "role": "user"
}

###
# Update User
PATCH {{baseUrl}}/user/{{userId}}
Content-Type: application/json

{
  "name": "John Doe Updated"
}

###
# Delete User
DELETE {{baseUrl}}/user/{{userId}}

### =========================================
### 3. RESOURCES (Fasilitas / Kamar)
### =========================================

### Create Resource (Bikin Kamar Baru)
POST {{baseUrl}}/resources
Content-Type: application/json

{
  "name": "Triple Room Luxury",
  "type": "standard",
  "location": "Lantai 1",
  "capacity": 3,
  "price_per_night": 500000,
  "facilities": ["TV", "AC", "Wi-Fi", "Extra Bed"]
}

### Resource Update
PATCH {{baseUrl}}/resources/{{resourceId}}
Content-Type: application/json

{
  "name": "Kamar Standard B"
}

### Resource Delete
DELETE {{baseUrl}}/resources/{{resourceId}}


### Get All Resources (Bisa ditambah filter: ?search=kamar&location=lantai1&type=vip)
GET {{baseUrl}}/resources?search=&location=&type=

### Get Single Resource
GET {{baseUrl}}/resources/{{resourceId}}


### resource with image create (sebaiknya postman karena mengambil file local)
POST {{baseUrl}}/resources
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxk

------WebKitFormBoundary7MA4YWxk
Content-Disposition: form-data; name="name"

Suite Room Mentri
------WebKitFormBoundary7MA4YWxk
Content-Disposition: form-data; name="type"

suite
------WebKitFormBoundary7MA4YWxk
Content-Disposition: form-data; name="location"

Lantai 3, VIP Area
------WebKitFormBoundary7MA4YWxk
Content-Disposition: form-data; name="capacity"

2
------WebKitFormBoundary7MA4YWxk
Content-Disposition: form-data; name="price_per_night"

1500000
------WebKitFormBoundary7MA4YWxk
Content-Disposition: form-data; name="facilities"

Wi-Fi
------WebKitFormBoundary7MA4YWxk
Content-Disposition: form-data; name="facilities"

AC
------WebKitFormBoundary7MA4YWxk
Content-Disposition: form-data; name="files"; filename="kamar1.jpeg"
Content-Type: image/jpeg

< ./test-assets/kamar1.jpeg


------WebKitFormBoundary7MA4YWxk
Content-Disposition: form-data; name="files"; filename="kamar2.jpeg"
Content-Type: image/jpeg

< ./test-assets/kamar2.jpeg

------WebKitFormBoundary7MA4YWxk--


# resource with image edit

PATCH http://localhost:3000/resources/042cee9c-01ce-49b4-96ed-466495d1eb6d
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxk

------WebKitFormBoundary7MA4YWxk
Content-Disposition: form-data; name="name"

Suite Room Mentri (Updated)
------WebKitFormBoundary7MA4YWxk
Content-Disposition: form-data; name="price_per_night"

1800000
------WebKitFormBoundary7MA4YWxk
Content-Disposition: form-data; name="facilities"

Wi-Fi
------WebKitFormBoundary7MA4YWxk
Content-Disposition: form-data; name="facilities"

AC
------WebKitFormBoundary7MA4YWxk
Content-Disposition: form-data; name="facilities"

Smart TV
------WebKitFormBoundary7MA4YWxk
Content-Disposition: form-data; name="files"; filename="kamar_baru.jpeg"
Content-Type: image/jpeg

< ./test-images/kamar1.jpeg

------WebKitFormBoundary7MA4YWxk--

### =========================================
### 4. SCHEDULES (Jadwal)
### =========================================



# NEW SCHEDULE
# Create Schedule (Buat 1 Jadwal)
###
POST {{baseUrl}}/schedule
Content-Type: application/json

{
  "resource_id": "{{resourceId}}",
  "start_time": "2026-08-05T12:15:00.000Z",
  "end_time": "2026-08-05T14:00:00.000Z",
  "status": "maintenance"
}

# Create Batch (lewat semenit bisa di kasi aksi. jika jadwal available)
### 
POST {{baseUrl}}/schedule/batch
Content-Type: application/json

[
  {
    "resource_id": "{{resourceIdVVIP}}",
    "start_time": "2026-07-27T09:00:00.000Z",
    "end_time": "2026-07-28T12:00:00.000Z",
    "status": "maintenance"
  },
  {
    "resource_id": "{{resourceIdVVIP}}",
    "start_time": "2026-07-28T12:01:00.000Z",
    "end_time": "2026-07-29T12:00:00.000Z",
    "status": "booked"
  }
]

### Get Find All
GET {{baseUrl}}/schedule
Content-Type: application/json

### Find By Id
GET {{baseUrl}}/schedule/{{scheduleId}}
Content-Type: application/json

### Find Busy Schedule (check pada jam 12 siang tanggal 26, jika tidak ada respon "ce857014-f4a7-4e63-b9ea-1d1d44c43f56", maka dia menangkap yg benar booked/maintenece pada rentang waktu realtime() - dia mencatat tanggal yg masi belum di lewati
GET {{baseUrl}}/schedule/busy/{{resourceId}}
Content-Type: application/json

### Update Schedule (skenario ubah waktu boking)
PATCH {{baseUrl}}/schedule/{{scheduleId}}
Content-Type: application/json

{
  "start_time": "2026-08-05T09:00:00+07:00",
  "end_time": "2026-08-05T12:00:00+07:00"
}

### Update Schedule (skenario ubah status jadi canceled, karena available otomtis sesuai tenggat waktu) 
PATCH {{baseUrl}}/schedule/{{scheduleId}}
Content-Type: application/json

{
  "status": "canceled"
}

### Delete Schedule
DELETE {{baseUrl}}/schedule/{{scheduleId}}

### =========================================
### 5. BOOKINGS (Penyewaan)
### =========================================


### 1. CREATE BOOKING (Otomatis bikin Schedule & Payment)
POST {{baseUrl}}/bookings
Content-Type: application/json

{
  "user_id": "{{userId}}",
  "resource_id": "{{resourceId}}",
  "start_time": "2026-08-05T01:00:00Z",
  "end_time": "2026-08-07T09:00:00Z",
  "notes": "perkara utc gua nginep",
  "payment_method": "qris" 
}
### Note payment_method sesuaikan dengan enum PaymentMethod lu (misal: 'transfer', 'cash', dll)

### 2. GET ALL BOOKINGS (Data lengkap + relasi)
GET {{baseUrl}}/bookings

### 3. GET BOOKINGS FILTER: ANTRIAN STAFF
GET {{baseUrl}}/bookings?status=pending

### 4. GET BOOKINGS FILTER: RIWAYAT USER TERTENTU
GET {{baseUrl}}/bookings?user_id={{userId}}

### 5. GET DETAIL BOOKING (By ID)
GET {{baseUrl}}/bookings/{{bookingId}}

### 6. UPDATE BOOKING: STAFF APPROVE
### (Otomatis melunaskan tabel payment)
PATCH {{baseUrl}}/bookings/{{bookingId}}
Content-Type: application/json

{
  "status": "approved",
  "notes": "Pembayaran telah dikonfirmasi oleh Admin"
}

### 7. UPDATE BOOKING: STAFF REJECT
### (Otomatis ubah schedule jadi CANCELED)
PATCH {{baseUrl}}/bookings/{{bookingId}}
Content-Type: application/json

{
  "status": "rejected",
  "notes": "Booking fiktif, utc kaga jelas"
}

### 8. UPDATE BOOKING: CHECK-IN / COMPLETED
PATCH {{baseUrl}}/bookings/{{bookingId}}
Content-Type: application/json

{
  "status": "approved",
  "notes": "Guest sudah check-out, kunci dikembalikan"
}

### 9. DELETE / CANCEL BOOKING (Oleh User/Staff)
### (Otomatis ubah schedule jadi CANCELED)
DELETE {{baseUrl}}/bookings/{{bookingId}}

### =========================================
### 6. AI BOT
### =========================================

# Test Chat with AI 
POST {{baseUrl}}/ai/chat
Content-Type: application/json

{
  "user_id": "{{userId}}",
  "message": "gua tertarik sama 505, lo bisa bantu bookingin?"
}
### =========================================
### 7. NOTIFICATIONS
### =========================================
### Notification
# Get All Notification
GET {{baseUrl}}/notifications
Content-Type: application/json

# unread-count
###
GET {{baseUrl}}/notifications/unread-count
Content-Type: application/json

# read-all
###
PATCH {{baseUrl}}/notifications/read-all
Content-Type: application/json

# read single notification
###
PATCH {{baseUrl}}/notifications/{{notificationId}}/read
Content-Type: application/json

### =========================================
### 8. REVIEW
### =========================================
POST {{baseUrl}}/reviews
Content-Type: application/json

{
  "booking_id": "{{bookingId}}",
  "rating": 5,
  "comment": "Luar biasa"
}

###
GET {{baseUrl}}/reviews/resource/{{resourceIdVVIP}}
Content-Type: application/json

###
GET {{baseUrl}}/reviews/{{reviewId}}
Content-Type: application/json

###
DELETE {{baseUrl}}/reviews/{{reviewId}}
Content-Type: application/json

### =========================================
### 9. ROOM IMAGE
### =========================================

###
POST {{baseUrl}}/room-images/upload
Content-Type: multipart/form-data

{
  "resource_id": "{{resourceId}}",
  "file": "https://pin.it/KCpJOaPgm" ,
  "is_primary": true 
}

### Get All
GET {{baseUrl}}/room-images
Content-Type: application/json

### Room Image Sekaligus Resource (bikin kamar sekaligus upload foto)
POST {{baseUrl}}/resources
Content-Type: multipart/form-data

{
  "name": "SSH Room",
  "type": "standard",
  "location": "Lantai 2, Blok Z",
  "capacity": 1,
  "price_per_night": 500000,
  "facilities": ["Wi-Fi", "AC", "TV", "Kamar Mandi Dalam"],
  "file": "https://pin.it/KCpJOaPgm" 
}
